// This file is part of the SJ Real Estate project
// It sets up the root layout for the Next.js application, including global styles and metadata.

import Layout from "@/layout/Layout";
import "@/styles/fonts.css";
import "@/styles/reset.css";
import "@/styles/globals.css";
import "@/styles/variables.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
